# Generated by Django 5.1.6 on 2025-03-21 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=9)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('image_url', models.URLField()),
            ],
        ),
    ]
