# Generated by Django 5.1.6 on 2025-03-21 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
